CREATE TABLE `results` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `results` JSON NOT NULL,
  `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

